lab 3
Hreaun/chatTree pull request #1
Opened 2020-10-25 09:05 UTC by Hreaun

@Aloomenon

2020-10-25 09:29 UTC, Aloomenon requested changes

2020-10-25 09:29 UTC, Aloomenon commented on src/main/java/Main.java
> +        receiver.interrupt();
Зачем? Что произойдет с receiver ?

2020-10-25 09:29 UTC, Aloomenon commented on src/main/java/Sender.java
> +            socket.close();
на другой поток не повлияет?

2020-10-25 11:01 UTC, Hreaun commented on src/main/java/Sender.java
> +            socket.close();
Повлияет, receiver выйдет с эксепшном

2020-10-25 11:05 UTC, Hreaun commented on src/main/java/Main.java
> +        receiver.interrupt();
receiver получит статус interrupted. receiver выходит из run либо с  IOException, либо при следующей проверке while (!isInterrupted()) с interrupted флагом, если был где-то в конце функции run и не производил действий с сокетом

2020-11-07 20:34 UTC, Aloomenon commented on src/main/java/Sender.java
> +            socket.close();
грустно конечно, да ладно. Принял.

2020-11-08 04:00 UTC, merged